
#' Expected Variables Present -- Output Generation
#'
#' Using the tabular output generated by `evp_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* || **required**
#'
#'   The tabular output produced by `evp_process`
#'
#' @param output_level *string* || defaults to `patient`
#'
#'   A string indicating the analysis level that should be reflected in the plot. All checks
#'   utilize this parameter EXCEPT `Single Site, Anomaly Detection, Cross-Sectional`, which
#'   executes a Jaccard index using only patient counts
#'
#' @param filter_variable *string or vector* || defaults to `NULL`
#'
#'   A string or vector with variable names that should be the focus of the analysis.
#'   Only a single value is accepted for the following checks:
#'   - `Multi Site, Exploratory, Longitudinal` (non-year time period)
#'   - `Multi Site, Anomaly Detection, Longitudinal`
#'   - `Single Site, Anomaly Detection, Longitudinal`
#'
#'   Multiple values (up to 3) are accepted for:
#'   - `Multi Site, Exploratory, Longitudinal` (year time period)
#'
#' @param large_n *boolean* || defaults to `FALSE`
#'
#'   For Multi-Site analyses, a boolean indicating whether the large N
#'   visualization, intended for a high volume of sites, should be used. This
#'   visualization will produce high level summaries across all sites, with an
#'   option to add specific site comparators via the `large_n_sites` parameter.
#'
#' @param large_n_sites *vector* || defaults to `NULL`
#'
#'   When `large_n = TRUE`, a vector of site names that can add site-level information
#'   to the plot for comparison across the high level summary information.
#'
#' @return This function will produce a graph to visualize the results
#'         from `evp_process` based on the parameters provided. The default
#'         output is typically a static ggplot or gt object, but interactive
#'         elements can be activated by passing the plot through `make_interactive_squba`.
#'         For a more detailed description of output specific to each check type,
#'         see the PEDSpace metadata repository
#'
#' @example inst/example-evp_process_output.R
#'
#' @export
#'
evp_output <- function(process_output,
                       output_level = 'patient',
                       filter_variable = NULL,
                       large_n = FALSE,
                       large_n_sites = NULL
                       ){

  ## extract output function
  output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()

  if('age_grp' %in% colnames(process_output)){facet <- 'age_grp'}else{facet <- NULL}

  if(output_function == 'evp_ss_exp_cs'){

    evp_output <- evp_ss_exp_cs(process_output = process_output,
                                output_level = output_level,
                                facet = facet)

  }else if(output_function == 'evp_ss_anom_cs'){

    evp_output <- evp_ss_anom_cs(process_output = process_output,
                                 facet = facet)

  }else if(output_function == 'evp_ss_exp_la'){

    evp_output <- evp_ss_exp_la(process_output = process_output,
                                output_level = output_level,
                                facet = facet)

  }else if(output_function == 'evp_ss_anom_la'){

    evp_output <- evp_ss_anom_la(process_output = process_output,
                                 output_level = output_level,
                                 facet = facet,
                                 filter_variable = filter_variable)

  }else if(output_function == 'evp_ms_exp_cs'){

    evp_output <- evp_ms_exp_cs(process_output = process_output,
                                output_level = output_level,
                                facet = facet,
                                large_n = large_n,
                                large_n_sites = large_n_sites)

  }else if(output_function == 'evp_ms_anom_cs'){

    evp_output <- evp_ms_anom_cs(process_output = process_output,
                                 output_level = output_level,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)

  }else if(output_function == 'evp_ms_exp_la'){

    evp_output <- evp_ms_exp_la(process_output = process_output,
                                output_level = output_level,
                                filter_variable = filter_variable,
                                facet = facet,
                                large_n = large_n,
                                large_n_sites = large_n_sites)

  }else if(output_function == 'evp_ms_anom_la'){

    evp_output <- evp_ms_anom_la(process_output = process_output,
                                 output_level = output_level,
                                 filter_variable = filter_variable,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)

  }else(cli::cli_abort('Please enter a valid output function for this check type.'))

  return(evp_output)

}

