
#' Expected Variables Present -- Output Generation
#'
#' Using the tabular output generated by `evp_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* | the output of the `evp_process` function
#' @param output_level *string* | the type of counts the output should summarise -- either `patient` or `row`
#' @param filter_variable *string* | for `ms_anom_la`, `ms_exp_la`, `ss_anom_la`, the single variable that
#' should be displayed in the output; can be any of the variables listed in the `evp_process` output
#'
#' @return a graph to visualize the results from `evp_process` based on the parameters provided; see documentation
#'         for individual subfunctions for details on specific output
#'
#' @example inst/example-evp_process_output.R
#'
#' @export
#'
evp_output <- function(process_output,
                       output_level,
                       filter_variable = NULL
                       # facet = NULL
                       ){

  ## extract output function
  output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()

  if('age_grp' %in% colnames(process_output)){facet <- 'age_grp'}else{facet <- NULL}

  if(output_function == 'evp_ss_exp_cs'){

    evp_output <- evp_ss_exp_cs(process_output = process_output,
                                output_level = output_level,
                                facet = facet)

  }else if(output_function == 'evp_ss_anom_cs'){

    evp_output <- evp_ss_anom_cs(process_output = process_output,
                                 facet = facet)

  }else if(output_function == 'evp_ss_exp_la'){

    evp_output <- evp_ss_exp_la(process_output = process_output,
                                output_level = output_level,
                                facet = facet)

  }else if(output_function == 'evp_ss_anom_la'){

    evp_output <- evp_ss_anom_la(process_output = process_output,
                                 output_level = output_level,
                                 facet = facet,
                                 filter_variable = filter_variable)

  }else if(output_function == 'evp_ms_exp_cs'){

    evp_output <- evp_ms_exp_cs(process_output = process_output,
                                output_level = output_level,
                                facet = facet)

  }else if(output_function == 'evp_ms_anom_cs'){

    evp_output <- evp_ms_anom_cs(process_output = process_output,
                                 output_level = output_level)

  }else if(output_function == 'evp_ms_exp_la'){

    evp_output <- evp_ms_exp_la(process_output = process_output,
                                output_level = output_level,
                                filter_variable = filter_variable,
                                facet = facet)

  }else if(output_function == 'evp_ms_anom_la'){

    evp_output <- evp_ms_anom_la(process_output = process_output,
                                 output_level = output_level,
                                 filter_variable = filter_variable)

  }else(cli::cli_abort('Please enter a valid output function for this check type.'))

  return(evp_output)

}

